/**
 * Created by Baird on 9/11/2020.
 */

@IsTest
private class VolPortalComponentsPresentTEST {
    @IsTest
    static void testBehavior() {
        // A Process Builder named "Opportunity" exists and is Active
        // An email template named "Alert_Organizer_New_Vol_Task"
        // An email alert named "Alert_Organizer_New_Vol_Task_Submitted" exists.
        // Is there a button for "Approve Vol Tasks" on the default campaign search list?
        // ApproveVolTasks, TEst and page
    }
}